config/routes.rb
SampleApp::Application.routes.draw do
  resources :document_list_requests

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/newsfeed', to: 'newsfeed#create', via: 'get'
  match '/hello', to: 'newsfeed#hello', via: 'get'
  match '/update', to: 'newsfeed#update', via: 'get'
  match '/rateCelebrity', to: 'newsfeed#rateCelebrity', via: 'get'
end

app/models/document_list_request.rb
class DocumentListRequest < ActiveRecord::Base
end

app/controllers/document_list_requests_controller.rb
class DocumentListRequestsController < ApplicationController
  before_action :set_document_list_request, only: [:show, :edit, :update, :destroy]

  # GET /document_list_requests
  # GET /document_list_requests.json
  def index
    @document_list_requests = DocumentListRequest.all
  end

  # GET /document_list_requests/1
  # GET /document_list_requests/1.json
  def show
  end

  # GET /document_list_requests/new
  def new
    @document_list_request = DocumentListRequest.new
  end

  # GET /document_list_requests/1/edit
  def edit
  end

  # POST /document_list_requests
  # POST /document_list_requests.json
  def create
    @document_list_request = DocumentListRequest.new(document_list_request_params)

    respond_to do |format|
      if @document_list_request.save
        format.html { redirect_to @document_list_request, notice: 'Document list request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document_list_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @document_list_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_list_requests/1
  # PATCH/PUT /document_list_requests/1.json
  def update
    respond_to do |format|
      if @document_list_request.update(document_list_request_params)
        format.html { redirect_to @document_list_request, notice: 'Document list request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document_list_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_list_requests/1
  # DELETE /document_list_requests/1.json
  def destroy
    @document_list_request.destroy
    respond_to do |format|
      format.html { redirect_to document_list_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_list_request
      @document_list_request = DocumentListRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_list_request_params
      params.require(:document_list_request).permit(:celebrityIds, :limit, :view, :orderBy, :profileId, :star0Factor, :star1Factor, :star2Factor, :star3Factor, :star4Factor, :docSentimentFactor, :celebSentimentFactor, :unblockThreshold)
    end
end

app/helpers/document_list_requests_helper.rb
module DocumentListRequestsHelper
end

app/views/document_list_requests/_form.html.erb
<%= form_for(@document_list_request) do |f| %>
  <% if @document_list_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_list_request.errors.count, "error") %> prohibited this document_list_request from being saved:</h2>

      <ul>
      <% @document_list_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :celebrityIds %><br>
    <%= f.text_field :celebrityIds %>
  </div>
  <div class="field">
    <%= f.label :limit %><br>
    <%= f.number_field :limit %>
  </div>
  <div class="field">
    <%= f.label :view %><br>
    <%= f.number_field :view %>
  </div>
  <div class="field">
    <%= f.label :orderBy %><br>
    <%= f.text_field :orderBy %>
  </div>
  <div class="field">
    <%= f.label :profileId %><br>
    <%= f.text_field :profileId %>
  </div>
  <div class="field">
    <%= f.label :star0Factor %><br>
    <%= f.text_field :star0Factor %>
  </div>
  <div class="field">
    <%= f.label :star1Factor %><br>
    <%= f.text_field :star1Factor %>
  </div>
  <div class="field">
    <%= f.label :star2Factor %><br>
    <%= f.text_field :star2Factor %>
  </div>
  <div class="field">
    <%= f.label :star3Factor %><br>
    <%= f.text_field :star3Factor %>
  </div>
  <div class="field">
    <%= f.label :star4Factor %><br>
    <%= f.text_field :star4Factor %>
  </div>
  <div class="field">
    <%= f.label :docSentimentFactor %><br>
    <%= f.text_field :docSentimentFactor %>
  </div>
  <div class="field">
    <%= f.label :celebSentimentFactor %><br>
    <%= f.text_field :celebSentimentFactor %>
  </div>
  <div class="field">
    <%= f.label :unblockThreshold %><br>
    <%= f.text_field :unblockThreshold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/document_list_requests/edit.html.erb
<h1>Editing document_list_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_list_request %> |
<%= link_to 'Back', document_list_requests_path %>

app/views/document_list_requests/index.html.erb
<h1>Listing document_list_requests</h1>


<p>
<%= link_to "API Documentation", "http://services.lexalytics.com:8090/display/MA/Content+Service+API" %>

<p>

<table>
  <thead>
    <tr>
      <th>Select</th>
      <th>ID</th>
      <th>Celebrityids</th>
      <th>Limit</th>
      <th>View</th>
      <th>Orderby</th>
      <th>Profileid</th>
      <th>Star0factor</th>
      <th>Star1factor</th>
      <th>Star2factor</th>
      <th>Star3factor</th>
      <th>Star4factor</th>
      <th>Docsentimentfactor</th>
      <th>Celebsentimentfactor</th>
      <th>Unblockthreshold</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @document_list_requests.each do |document_list_request| %>
      <tr>
        <td align=center><%= link_to "Select", "/newsfeed?dlrid=#{document_list_request.id}" %></td>
        <td align=center><%= document_list_request.id%></td>
        <td align=center><%= document_list_request.celebrityIds %></td>
        <td align=center><%= document_list_request.limit %></td>
        <td align=center><%= document_list_request.view %></td>
        <td align=center><%= document_list_request.orderBy %></td>
        <td align=center><%= document_list_request.profileId %></td>
        <td align=center><%= document_list_request.star0Factor %></td>
        <td align=center><%= document_list_request.star1Factor %></td>
        <td align=center><%= document_list_request.star2Factor %></td>
        <td align=center><%= document_list_request.star3Factor %></td>
        <td align=center><%= document_list_request.star4Factor %></td>
        <td align=center><%= document_list_request.docSentimentFactor %></td>
        <td align=center><%= document_list_request.celebSentimentFactor %></td>
        <td align=center><%= document_list_request.unblockThreshold %></td>
        <td align=center><%= link_to 'Show', document_list_request %></td>
        <td align=center><%= link_to 'Edit', edit_document_list_request_path(document_list_request) %></td>
        <td><%= link_to 'Destroy', document_list_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document List Request', new_document_list_request_path %>
<p>
<!--<%= link_to "View Newsfeed", "/newsfeed" %>-->

app/views/document_list_requests/new.html.erb
<h1>New document_list_request</h1>

<%= render 'form' %>

<%= link_to 'Back', document_list_requests_path %>

app/views/document_list_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Celebrityids:</strong>
  <%= @document_list_request.celebrityIds %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @document_list_request.limit %>
</p>

<p>
  <strong>View:</strong>
  <%= @document_list_request.view %>
</p>

<p>
  <strong>Orderby:</strong>
  <%= @document_list_request.orderBy %>
</p>

<p>
  <strong>Profileid:</strong>
  <%= @document_list_request.profileId %>
</p>

<p>
  <strong>Star0factor:</strong>
  <%= @document_list_request.star0Factor %>
</p>

<p>
  <strong>Star1factor:</strong>
  <%= @document_list_request.star1Factor %>
</p>

<p>
  <strong>Star2factor:</strong>
  <%= @document_list_request.star2Factor %>
</p>

<p>
  <strong>Star3factor:</strong>
  <%= @document_list_request.star3Factor %>
</p>

<p>
  <strong>Star4factor:</strong>
  <%= @document_list_request.star4Factor %>
</p>

<p>
  <strong>Docsentimentfactor:</strong>
  <%= @document_list_request.docSentimentFactor %>
</p>

<p>
  <strong>Celebsentimentfactor:</strong>
  <%= @document_list_request.celebSentimentFactor %>
</p>

<p>
  <strong>Unblockthreshold:</strong>
  <%= @document_list_request.unblockThreshold %>
</p>

<%= link_to 'Edit', edit_document_list_request_path(@document_list_request) %> |
<%= link_to 'Back', document_list_requests_path %>